[package]
name = "ec-slimloader-descriptors"
version = "0.1.0"
edition = "2021"

[dependencies]
crc = "3.2.1"
constmuck = { version = "1.1.0", features = ["derive"] }
bytemuck = { version = "1.21.0", features = ["derive"] }
